# Generated by Django 3.0.3 on 2020-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=256)),
                ('album_visibility', models.CharField(max_length=10)),
                ('album_description', models.CharField(max_length=1024)),
            ],
        ),
    ]
