# Generated by Django 3.0.3 on 2020-02-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
