# Generated by Django 3.0.3 on 2020-02-23 16:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200223_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/queries', location='/Users/chavez/Desktop/photomug/backend/media'), unique=True, upload_to='queries')),
            ],
        ),
    ]
