# Generated by Django 3.0.3 on 2020-02-23 17:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesearch',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/queries', location='/Users/chavez/Desktop/photomug/backend/media'), upload_to='queries'),
        ),
    ]
