# Generated by Django 3.0.3 on 2020-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200223_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesearch',
            name='file',
            field=models.FileField(upload_to='queries'),
        ),
    ]
