# Generated by Django 3.0.3 on 2020-02-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200223_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesearch',
            name='file',
            field=models.FileField(storage='queries', upload_to=''),
        ),
    ]
