# Generated by Django 3.0.3 on 2020-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200223_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesearch',
            name='file',
            field=models.FileField(storage='/Users/chavez/Desktop/photomug/backend/media/queries', upload_to=''),
        ),
    ]
