# Generated by Django 3.0.3 on 2020-02-23 18:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200223_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesearch',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/Users/chavez/Desktop/photomug/backend/media/queries', location='/Users/chavez/Desktop/photomug/backend/media/queries'), upload_to='queries'),
        ),
    ]
