# Generated by Django 3.0.3 on 2020-02-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_photolike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photolike',
            name='user',
        ),
    ]
