# Generated by Django 3.0.3 on 2020-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_photolike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
