# Generated by Django 3.0.3 on 2020-02-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_file_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoLike',
        ),
    ]
