# Generated by Django 3.0.3 on 2020-02-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_photolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Album'),
        ),
    ]
